dist: bionic
sudo: false

language: generic

install:
  - 'sudo apt-get -y install make cmake ninja-build'
  - 'sudo apt-get install -y libgl1-mesa-dev mesa-common-dev'

script:
  - 'cd deps'
  - 'mkdir build'
  - 'cd build'
  - 'cmake -G Ninja ..'
  - 'ninja -j 1 -v'